xbbcode.settings:
  type: config_object
  label: 'Global XBBCode settings'
  mapping:
    tags:
      type: xbbcode.plugin_collection

filter_settings.xbbcode:
  type: mapping
  label: 'XBBCode filter-specific settings'
  mapping:
    override:
      type: boolean
      label: 'Override the global settings'
    linebreaks:
      type: boolean
      label: 'Convert linebreaks'
    tags:
      type: xbbcode.plugin_collection

xbbcode.plugin_collection:
  type: sequence
  label: 'Collection of tag plugins'
  sequence:
    type: xbbcode.plugin

xbbcode.plugin:
  type: mapping
  label: 'Settings for one tag plugin'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: string
      label: 'Name'
    status:
      type: boolean
      label: 'Status'

xbbcode.tag.*:
  type: xbbcode_tag

xbbcode_tag:
  type: config_entity
  label: 'XBBCode tag'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
    description:
      type: text
      label: 'Description'
    name:
      type: string
      label: 'Default name'
    selfclosing:
      type: boolean
      label: 'Self-closing'
    attached:
      type: mapping
      mapping:
        # Only the library key is supported for now.
        library:
          type: sequence
          label: 'Libraries'
          sequence:
            type: string
      label: 'Attachments'
    sample:
      type: text
      label: 'Sample code'
    template_code:
      type: string
      label: 'Inline template code'
    template_file:
      type: string
      label: 'Template file'
    settings:
      type: xbbcode.tag_settings.[%parent.id]
    editable:
      type: boolean
      label: 'Editable'
