xbbcode.settings:
  type: mapping
  label: 'Global XBBCode settings'
  mapping:
    tags:
      type: xbbcode.tag_collection

filter_settings.xbbcode:
  type: mapping
  label: 'XBBCode filter-specific settings'
  mapping:
    override:
      type: boolean
      label: 'Override the global settings'
    linebreaks:
      type: boolean
      label: 'Convert linebreaks'
    tags:
      type: xbbcode.tag_collection

xbbcode.tag_collection:
  type: sequence
  label: 'Tag collection'
  sequence:
    type: xbbcode.tag

xbbcode.tag:
  type: mapping
  label: 'XBBCode tag'
  mapping:
    id:
      type: string
      label: 'ID'
    provider:
      type: string
      label: 'Provider'
    status:
      type: boolean
      label: 'Status'
    settings:
      type: xbbcode.tag_settings.[%parent.id]

xbbcode.tag_settings.*:
  type: mapping
  label: 'Tag settings'