<?php
// $Id$

function xbbcode_table_xbbcode_info($op = 'list', $delta = '', $tag = NULL) {
  $tags['table'] = array(
    'callback' => 'xbbcode_table_render',
    'description' => 'Create a table from comma-separated data.',
    'sample' => '[table=Left,!Centered,#Right]
Lorem,Ipsum,Dolor
Sit,amet,consectetur
[/table]');
  return $tags;
}


function xbbcode_table_render($tag) {
  $rows = explode("\n", trim($tag->content));
  if ($tag->option) {
    $headers = explode(",", $tag->option);
    foreach ($headers as $i => $header) {
      if (preg_match('/^([#!])(.+)$/', $header, $match)) {
        $headers[$i] = $match[2];
        $align[$i] = $match[1] == '#' ? 'right' : 'center';
      }
      else $align[$i] = 'left';
    }
  }
  else {
    $headers = array();
  }
  foreach ($rows as $row) {
    $row = explode(",", $row);
    if ($headers) {
      foreach ($row as $i => $cell) {
        $row[$i] = array(
          'data' => $cell,
          'style' => 'text-align:' . $align[$i],
        );
      }
    }
    $cells[] = $row;
  }

  $html = theme('table', array('header' => $headers, 'rows' => $cells));
  // strip linebreaks
  $html = str_replace("\n", "", $html);
  return $html;
}
