Extensible BBCode: XBBCodeFilter Class Reference
XBBCodeFilter Class Reference
Public Member Functions
__construct (array $configuration, $plugin_id, $plugin_definition)
tags ($plugin_id=NULL)
tagsByName ($name=NULL)
settingsForm (array $form, FormStateInterface $form_state)
tips ($long=FALSE)
process ($text, $langcode)
Detailed Description
Provides a filter that converts BBCode to HTML.
(id = "xbbcode", title = ("Convert BBCode into HTML."), type = Drupal::TYPE_MARKUP_LANGUAGE, settings = { "override" = FALSE, "linebreaks" = TRUE, "tags" = {} })
Definition at line 35 of file XBBCodeFilter.php.
Constructor & Destructor Documentation
__construct (array $configuration, $plugin_id, $plugin_definition)
{}
Definition at line 57 of file XBBCodeFilter.php.
References XBBCodeFilter\tags().
Member Function Documentation
process ($text, $langcode)
{}
Definition at line 213 of file XBBCodeFilter.php.
References XBBCodeFilter\tagsByName().
Referenced by XBBCodeFilter\tips().
settingsForm (array $form, FormStateInterface $form_state)
{}
Definition at line 121 of file XBBCodeFilter.php.
References PluginSelectionForm\buildPluginForm(), and XBBCodeFilter\tags().
tags ($plugin_id = NULL)
Return the TagPluginCollection, or find a particular tag by its ID.
This collection contains all available plugins, enabled or not.
Parameters
string $plugin_id The plugin ID (optional).
Returns
TagPluginCollection | TagPluginInterface Either the entire collection or one tag plugin.
Definition at line 79 of file XBBCodeFilter.php.
Referenced by XBBCodeFilter\__construct(), XBBCodeFilter\settingsForm(), and XBBCodeFilter\tagsByName().
tagsByName ($name = NULL)
Return the enabled pluging indexed by name, or find one plugin by name.
Parameters
string $name The name of the tag plugin.
Returns
array | TagPluginInterface Either the entire array or one tag plugin.
Definition at line 97 of file XBBCodeFilter.php.
References XBBCodeFilter\tags().
Referenced by XBBCodeFilter\process(), and XBBCodeFilter\tips().
tips ($long = FALSE)
{}
Definition at line 154 of file XBBCodeFilter.php.
References XBBCodeFilter\process(), and XBBCodeFilter\tagsByName().
The documentation for this class was generated from the following file:
xbbcode/src/Plugin/Filter/XBBCodeFilter.php